bulk:
  api:
    url: https://api-01.moengage.com/v1/transition/1NZ9MZFA546B7ZLQALH1K1EE?app_id=1NZ9MZFA546B7ZLQALH1K1EE
app:
  id: ${env.MOENGAGE_DATAAPI_ID}
server:
  port: 5000
spring:
  data:
    mongodb:
      uri: ${env.MONGO_URL}
      database: ${env.MONGO_DBNAME}
secret:
  key: ${env.MOENGAGE_DATAAPI_KEY}
  dbURL: ${env.REDSHIFT_CLUSTER_DBURL}
  masterUsername: connectiontest
  masterUserPassword: Password123